version: '3'

services:
  node:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    image: gusflopes/node-example
    container_name: node
    restart: always
    networks:
      - fc-docker
    # ports:
      # - "3000:3000"
    tty: true
    depends_on:
      - db-mysql
      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fc-docker
    ports:
      - "8080:8080"
    tty: true

  db-mysql:
    image: mysql:5.7
    container_name: db-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    # ports:
    #   - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql
    environment:
      MYSQL_DATABASE: node-db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - fc-docker

networks:
  fc-docker:
    driver: bridge
